### ISSUE TITLE
[doc] add basic bundle installation info to readme doc

### ISSUE THREAD

**Issue by jpoesen** [psynaptic/php-drupal.tmbundle#10]
[edit] sorry, issue already reported and solved on http://drupal.org/node/838632

Hi. Awesome bundle.

For completeness' sake, it might be good idea to mention in the readme that this bundle can be installed by going to ~/Library/Application Support/textmate/bundles and then cloning  https://github.com/psynaptic/php-drupal.tmbundle.git there.

Thx.
J.

**Comment by psynaptic** [comment]
I did this yesterday. Sorry it took so long.
