### ISSUE TITLE
use of cmd-shift-L KeyCommand for Wrap in t()

### ISSUE THREAD

**Issue by jcsiegrist** [psynaptic/php-drupal.tmbundle#2]
cmd-shift-L is a standard TexMate Shortcut to select the current line. Overriding this command with the wrap in t() snippet really threw me off. It is easily "fixed" by editing the bundle, but maybe it might be a better idea using a different shortcut.

**Comment by psynaptic** [comment]
ahh, thanks for catching this. I totally forgot about that command. I'll change it now. What can we use instead?

**Comment by webflo** [comment]
fixed in https://github.com/psynaptic/php-drupal.tmbundle/commit/cf75e013ac6aaed624cf5d7d77d93aa94d62009d
