### ISSUE TITLE
Filenames breaking on Windows.

### ISSUE THREAD

**Issue by PJnes** [psynaptic/php-drupal.tmbundle#23]
I know Textmate doesn't run on Windows, but I use e, and it supports the use of tmbundles. Use of < and > in the snippet filenames causes a clone to choke.

Any chance you could rename the files to use only characters supported on all 3 operating systems?

**Comment by psynaptic** [comment]
I'll happily take a patch :)

**Comment by PJnes** [comment]
Well with that knowledge I'll probably get going on it tomorrow then!
